In [1]:
from google.colab import drive
drive.mount("/F")

Mounted at /F


In [2]:
import pandas as pd
import tensorflow as tf

In [3]:
base = pd.read_csv('/F/My Drive/Maratona/Regressão Linear/house_prices.csv')

In [4]:
base.head()

id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]

In [5]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [6]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [7]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [9]:
base = pd.read_csv('/F/My Drive/Maratona/Regressão Linear/house_prices.csv', usecols = colunas_usadas)

In [10]:
base.head()

price  bedrooms  bathrooms  ...  zipcode      lat     long
0  221900.0         3       1.00  ...    98178  47.5112 -122.257
1  538000.0         3       2.25  ...    98125  47.7210 -122.319
2  180000.0         2       1.00  ...    98028  47.7379 -122.233
3  604000.0         4       3.00  ...    98136  47.5208 -122.393
4  510000.0         3       2.00  ...    98074  47.6168 -122.045

[5 rows x 17 columns]

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler_x = MinMaxScaler()

In [13]:
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform( base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long'] ] ) 

In [14]:
base.head()

price  bedrooms  bathrooms  ...   zipcode       lat      long
0  221900.0  0.090909    0.12500  ...  0.893939  0.571498  0.217608
1  538000.0  0.090909    0.28125  ...  0.626263  0.908959  0.166113
2  180000.0  0.060606    0.12500  ...  0.136364  0.936143  0.237542
3  604000.0  0.121212    0.37500  ...  0.681818  0.586939  0.104651
4  510000.0  0.090909    0.25000  ...  0.368687  0.741354  0.393688

[5 rows x 17 columns]

In [15]:
scaler_y = MinMaxScaler()

In [16]:
base[['price']] = scaler_y.fit_transform(base[['price']])

In [17]:
base.head()

price  bedrooms  bathrooms  ...   zipcode       lat      long
0  0.019266  0.090909    0.12500  ...  0.893939  0.571498  0.217608
1  0.060721  0.090909    0.28125  ...  0.626263  0.908959  0.166113
2  0.013770  0.060606    0.12500  ...  0.136364  0.936143  0.237542
3  0.069377  0.121212    0.37500  ...  0.681818  0.586939  0.104651
4  0.057049  0.090909    0.25000  ...  0.368687  0.741354  0.393688

[5 rows x 17 columns]

In [18]:
X = base.drop('price', axis =1)
Y = base.price

In [19]:
X.head()

bedrooms  bathrooms  sqft_living  ...   zipcode       lat      long
0  0.090909    0.12500     0.067170  ...  0.893939  0.571498  0.217608
1  0.090909    0.28125     0.172075  ...  0.626263  0.908959  0.166113
2  0.060606    0.12500     0.036226  ...  0.136364  0.936143  0.237542
3  0.121212    0.37500     0.126038  ...  0.681818  0.586939  0.104651
4  0.090909    0.25000     0.104906  ...  0.368687  0.741354  0.393688

[5 rows x 16 columns]

In [20]:
Y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [21]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [22]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [23]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, Y_treinamento, Y_teste = train_test_split(X, Y, test_size = 0.3)

In [24]:
X_treinamento.shape

(15129, 16)

In [25]:
Y_treinamento.shape

(15129,)

In [26]:
features_col = colunas
labels = 'medv'

In [27]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpundfggts', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [28]:
import numpy as np

In [29]:
def input_train_fn(features, labels, training=True, batch_size=32):
    """An input function for training or evaluating"""
    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))

    # Shuffle and repeat if you are in training mode.
    if training:
        dataset = dataset.shuffle(10000)
    
    return dataset.batch(batch_size)

In [30]:
regressor.train(input_fn = lambda: input_train_fn(X_treinamento, Y_treinamento, training = True), steps= 10000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
INFO:tensorflow:Calling model_fn.


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1727: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpundfggts/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 0.008332016, step = 0
INFO:tensorflow:global_step/sec: 506.542
INFO:tensorflow:loss = 0.0006726757, step = 100 (0.199 sec)
INFO:tensorflow:global_step/sec: 863.461
INFO:tensorflow:loss = 0.0009678663, step = 200 (0.116 sec)
INFO:tensorflow:global_step/sec: 847.343
INFO:tensorflow:loss = 0.0010296584, step = 300 (0.121 sec)
INFO:tensorflow:global_step/sec: 861.66
INFO:tensorflow:loss = 0.0012106177, step = 400 (0.113 sec)
INFO:te

In [31]:
metricas_treinamento = regressor.evaluate(input_fn = lambda: input_train_fn(X_treinamento, Y_treinamento, training = True), steps= 10000)

INFO:tensorflow:Calling model_fn.


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1727: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '


INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2021-01-26T20:28:08Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpundfggts/model.ckpt-473
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.78174s
INFO:tensorflow:Finished evaluation at 2021-01-26-20:28:09
INFO:tensorflow:Saving dict for global step 473: average_loss = 0.0008606177, global_step = 473, label/mean = 0.061129738, loss = 0.0008604259, prediction/mean = 0.07351466
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 473: /tmp/tmpundfggts/model.ckpt-473


In [32]:
metricas_teste = regressor.evaluate(input_fn = lambda: input_train_fn(X_teste, Y_teste, training = False), steps= 10000)

INFO:tensorflow:Calling model_fn.


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1727: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '


INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2021-01-26T20:28:16Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpundfggts/model.ckpt-473
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.44719s
INFO:tensorflow:Finished evaluation at 2021-01-26-20:28:17
INFO:tensorflow:Saving dict for global step 473: average_loss = 0.0009106536, global_step = 473, label/mean = 0.06068122, loss = 0.00091046974, prediction/mean = 0.07325713
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 473: /tmp/tmpundfggts/model.ckpt-473


In [33]:
metricas_treinamento

{'average_loss': 0.0008606177,
 'global_step': 473,
 'label/mean': 0.061129738,
 'loss': 0.0008604259,
 'prediction/mean': 0.07351466}

In [34]:
metricas_teste

{'average_loss': 0.0009106536,
 'global_step': 473,
 'label/mean': 0.06068122,
 'loss': 0.00091046974,
 'prediction/mean': 0.07325713}

In [35]:
def input_t_fn(features, training=True, batch_size=32):
    """An input function for training or evaluating"""
    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices(dict(features))

    # Shuffle and repeat if you are in training mode.
    if training:
        dataset = dataset.shuffle(10000)
    
    return dataset.batch(batch_size)

In [36]:
def make_input_fn(data_df, label_df, num_epochs=10, shuffle=True, batch_size=32):
  def input_function():
    ds = tf.data.Dataset.from_tensor_slices((dict(data_df), label_df))
    if shuffle:
      ds = ds.shuffle(1000)
    ds = ds.batch(batch_size).repeat(num_epochs)
    return ds
  return input_function

In [37]:
previsoes = list(regressor.predict(input_fn= make_input_fn(X_teste, Y_teste, num_epochs=1, shuffle=False )))

INFO:tensorflow:Calling model_fn.


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1727: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '


INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpundfggts/model.ckpt-473
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [38]:
list(previsoes)

[{'predictions': array([0.04317492], dtype=float32)},
 {'predictions': array([0.02355967], dtype=float32)},
 {'predictions': array([0.13612524], dtype=float32)},
 {'predictions': array([0.0568175], dtype=float32)},
 {'predictions': array([0.14922066], dtype=float32)},
 {'predictions': array([0.02475056], dtype=float32)},
 {'predictions': array([0.05739611], dtype=float32)},
 {'predictions': array([0.10676347], dtype=float32)},
 {'predictions': array([0.04098165], dtype=float32)},
 {'predictions': array([0.0363187], dtype=float32)},
 {'predictions': array([0.05526113], dtype=float32)},
 {'predictions': array([0.17900383], dtype=float32)},
 {'predictions': array([0.03890737], dtype=float32)},
 {'predictions': array([0.04735211], dtype=float32)},
 {'predictions': array([0.04927545], dtype=float32)},
 {'predictions': array([0.05731865], dtype=float32)},
 {'predictions': array([0.05221289], dtype=float32)},
 {'predictions': array([0.06583978], dtype=float32)},
 {'predictions': array([0.0937

In [39]:
val_previ = []

In [40]:
for p in regressor.predict(input_fn= make_input_fn(X_teste, Y_teste, num_epochs=1, shuffle=False )):
  val_previ.append(p['predictions'])

INFO:tensorflow:Calling model_fn.


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1727: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '


INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpundfggts/model.ckpt-473
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [41]:
val_previ

[array([0.04317492], dtype=float32),
 array([0.02355967], dtype=float32),
 array([0.13612524], dtype=float32),
 array([0.0568175], dtype=float32),
 array([0.14922066], dtype=float32),
 array([0.02475056], dtype=float32),
 array([0.05739611], dtype=float32),
 array([0.10676347], dtype=float32),
 array([0.04098165], dtype=float32),
 array([0.0363187], dtype=float32),
 array([0.05526113], dtype=float32),
 array([0.17900383], dtype=float32),
 array([0.03890737], dtype=float32),
 array([0.04735211], dtype=float32),
 array([0.04927545], dtype=float32),
 array([0.05731865], dtype=float32),
 array([0.05221289], dtype=float32),
 array([0.06583978], dtype=float32),
 array([0.09370014], dtype=float32),
 array([0.08665106], dtype=float32),
 array([0.03505681], dtype=float32),
 array([0.06202558], dtype=float32),
 array([0.20109692], dtype=float32),
 array([0.03992399], dtype=float32),
 array([0.01461026], dtype=float32),
 array([0.09012014], dtype=float32),
 array([0.04530501], dtype=float32),
 ar

In [42]:
val_previ = np.asarray(val_previ)

In [43]:
val_previ

array([[0.04317492],
       [0.02355967],
       [0.13612524],
       ...,
       [0.0660754 ],
       [0.07145372],
       [0.09526612]], dtype=float32)

In [44]:
val_previ = scaler_y.inverse_transform(val_previ)

In [45]:
Y_teste2 = Y_teste.values.reshape(-1,1)

In [46]:
Y_teste2.shape

(6484, 1)

In [47]:
Y_teste2 = scaler_y.inverse_transform(Y_teste2)

In [48]:
Y_teste2

array([[312500.],
       [208000.],
       [756000.],
       ...,
       [329000.],
       [390000.],
       [525000.]])

In [49]:
from sklearn.metrics import mean_absolute_error

In [50]:
mae = mean_absolute_error(Y_teste2, val_previ)

In [51]:
mae

159513.22715346745