In [1]:
import tensorflow as tf
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data

In [4]:
Y = iris.target

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler_x = StandardScaler()

In [7]:
X = scaler_x.fit_transform(X)

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
onehot = OneHotEncoder(categories = 'auto')

In [10]:
Y = Y.reshape(len(Y), 1)

In [11]:
Y.shape

(150, 1)

In [12]:
Y = onehot.fit_transform(Y).toarray()

In [13]:
Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_treinamento, X_teste, Y_treinamento, Y_teste = train_test_split(X, Y, test_size = 0.2)

In [16]:
X_treinamento.shape

(120, 4)

In [17]:
import numpy as np

In [18]:
neuronios_entrada = X.shape[1]

In [19]:
neuronios_entrada

4

In [20]:
neuronios_oculta =int( np.ceil( (X.shape[1] + Y.shape[1] ) / 2) )

In [21]:
neuronios_oculta

4

In [22]:
neuronios_saida = Y.shape[1]

In [23]:
neuronios_saida

3

In [24]:
W = {'oculta': tf.Variable(tf.keras.backend.random_normal([neuronios_entrada, neuronios_oculta])),
     'saida': tf.Variable(tf.keras.backend.random_normal([neuronios_oculta, neuronios_saida]))}

In [25]:
b = {'oculta': tf.Variable(tf.keras.backend.random_normal([neuronios_oculta])),
     'saida': tf.Variable(tf.keras.backend.random_normal([neuronios_saida]))}

In [26]:
batch_size = 10

In [27]:
batch_total = int ( len( X_treinamento ) / batch_size )

In [28]:
batch_total

12

In [29]:
x_batches = np.array_split( X_treinamento, batch_total )

In [30]:
X_treinamento.shape

(120, 4)

In [31]:
X_teste.shape

(30, 4)

In [32]:
Xb = tf.Variable(x_batches)

In [33]:
Xb.shape

TensorShape([12, 10, 4])

In [34]:
Xb[0]

<tf.Tensor: shape=(10, 4), dtype=float64, numpy=
array([[ 1.28034050e+00,  9.82172869e-02,  9.33270550e-01,
         1.18556721e+00],
       [ 2.24968346e+00, -1.05276654e+00,  1.78583195e+00,
         1.44883158e+00],
       [-7.79513300e-01,  7.88807586e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-9.00681170e-01, -1.28296331e+00, -4.30827696e-01,
        -1.30754636e-01],
       [ 1.15917263e+00, -5.92373012e-01,  5.92245988e-01,
         2.64141916e-01],
       [-5.25060772e-02, -8.22569778e-01,  7.62758269e-01,
         9.22302838e-01],
       [-1.73673948e-01,  3.09077525e+00, -1.28338910e+00,
        -1.05217993e+00],
       [ 3.10997534e-01, -5.92373012e-01,  5.35408562e-01,
         8.77547895e-04],
       [ 9.16836886e-01, -1.31979479e-01,  3.64896281e-01,
         2.64141916e-01],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00]])>

In [35]:
np.argmax(X_treinamento,1).shape

(120,)

In [36]:
model = tf.keras.models.Sequential()

In [37]:
model.add( tf.keras.layers.Dense(units = neuronios_oculta, activation = 'relu' ) )

In [38]:
model.add( tf.keras.layers.Dropout( 0.1 ) )

In [39]:
model.add( tf.keras.layers.Dense(units=neuronios_saida, activation = 'softmax' ) )

In [40]:
model.compile(loss = 'mse', optimizer= 'SGD' , metrics=['binary_accuracy'])

In [41]:
model.fit(X_treinamento, Y_treinamento, epochs=10000, verbose=0)

In [42]:
print( model.predict( X_teste ).round() )

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
print ( Y_teste )

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
from sklearn.metrics import accuracy_score

In [45]:
taxa_acerto = accuracy_score(Y_teste, model.predict( X_teste ).round() )

In [46]:
taxa_acerto

1.0

In [47]:
r1 = tf.argmax(model.predict( X_teste ) , 1)

In [48]:
r2 = np.argmax(Y_teste, 1)

In [49]:
tax_acc = accuracy_score(r2, r1 )

In [50]:
tax_acc

1.0