In [1]:
from sklearn import datasets
iris = datasets.load_iris()

In [2]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
Y = iris.target
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [5]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder()
Y.shape

(150,)

In [6]:
Y = Y.reshape(-1, 1)
Y.shape

(150, 1)

In [7]:
Y = onehot.fit_transform(Y).toarray()
Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [8]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, Y_treinamento, Y_teste = train_test_split(X, Y, test_size = 0.3, random_state = 42)

In [9]:
X_treinamento.shape

(105, 4)

In [10]:
X_teste.shape

(45, 4)

In [11]:
import tensorflow as tf
import numpy as np

In [12]:
tf.random.set_seed(42)

In [13]:
neuronios_entrada = X.shape[1]
neuronios_entrada

4

In [15]:
neuronios_oculta = int(np.ceil((X.shape[1] + Y.shape[1]) / 2))
neuronios_oculta

4

In [16]:
neuronios_saida = Y.shape[1]
neuronios_saida

3

In [20]:
W = {'oculta': tf.Variable( tf.keras.backend.random_normal([neuronios_entrada, neuronios_oculta]) ),
     'saida': tf.Variable( tf.keras.backend.random_normal([neuronios_oculta, neuronios_saida]))}

In [25]:
b = {'oculta': tf.Variable( tf.keras.backend.random_normal([neuronios_oculta])),
     'saida': tf.Variable( tf.keras.backend.random_normal([neuronios_saida]))}

In [27]:
X_treinamento = tf.convert_to_tensor(X_treinamento, dtype = tf.float32, name = 'X')
Y_treinamento = tf.convert_to_tensor(Y_treinamento, dtype = tf.float32, name = 'Y')
X_teste = tf.convert_to_tensor(X_teste, dtype = tf.float32, name = 'X')
Y_teste = tf.convert_to_tensor(Y_teste, dtype = tf.float32, name = 'Y')

In [28]:
def mlp(x, W, bias):
    camada_oculta = tf.add(tf.matmul(x, W['oculta']), bias['oculta'])
    camada_oculta_ativacao = tf.nn.relu(camada_oculta)
    camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W['saida']), b['saida'])
    return camada_saida

In [30]:
with tf.GradientTape() as tape:
    modelo = mlp(X_treinamento, W, b)
    erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels = Y_treinamento, logits = modelo))

In [31]:
var_list = [W['oculta'], W['saida'], b['oculta'], b['saida']]

In [32]:
W['oculta']

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 1.5236708 , -1.0299263 ,  0.6491818 ,  2.190112  ],
       [ 0.35098448, -1.0597771 ,  0.81969124,  0.3814578 ],
       [-1.9837582 ,  0.23649706,  0.50715417,  0.16612624],
       [ 0.49137434,  1.1304348 ,  0.09426894,  2.2604814 ]],
      dtype=float32)>

In [33]:
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.0001)
gradientes = tape.gradient(erro, var_list)
otimizador.apply_gradients(zip(gradientes, var_list))

<tf.Variable 'UnreadVariable' shape=() dtype=int64, numpy=1>

In [34]:
W['oculta']

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 1.5237708 , -1.0298263 ,  0.6491818 ,  2.1900122 ],
       [ 0.3508845 , -1.0598772 ,  0.81969124,  0.3815578 ],
       [-1.9836582 ,  0.2363971 ,  0.50715417,  0.16602623],
       [ 0.49147433,  1.1303347 ,  0.09426894,  2.2603815 ]],
      dtype=float32)>

In [35]:
dataset = tf.data.Dataset.from_tensor_slices((X_treinamento, Y_treinamento))

In [36]:
batch_size = 8
dataset = dataset.batch(batch_size)

In [39]:
next(iter(dataset))

(<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
 array([[-0.4160097 , -1.5131601 , -0.03296571, -0.26238683],
        [ 0.5533333 , -0.592373  ,  0.76275826,  0.3957741 ],
        [ 0.6745011 ,  0.09821729,  0.99010795,  0.79067063],
        [ 0.91683686, -0.13197948,  0.36489627,  0.26414192],
        [ 1.6438441 ,  1.249201  ,  1.3311325 ,  1.712096  ],
        [-0.17367394, -0.36217624,  0.25122142,  0.13250974],
        [ 2.1285155 , -0.13197948,  1.6153197 ,  1.1855673 ],
        [-0.29484183, -0.13197948,  0.4217337 ,  0.3957741 ]],
       dtype=float32)>, <tf.Tensor: shape=(8, 3), dtype=float32, numpy=
 array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.]], dtype=float32)>)

In [40]:
dataset = tf.data.Dataset.from_tensor_slices((X_treinamento, Y_treinamento)).batch(batch_size)

In [41]:
for epoca in range(3000):
    for X_batch, y_batch in dataset:
        erro_medio = 0.0
        with tf.GradientTape() as tape:
            modelo = mlp(X_batch, W, b)
            erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels = y_batch, logits = modelo))
        gradientes = tape.gradient(erro, var_list)
        otimizador.apply_gradients(zip(gradientes, var_list))
        erro_medio += erro.numpy()
    if epoca % 500 == 0:
        print('Época: ' + str((epoca + 1)) + ' erro: ' + str(erro_medio))

Época: 1 erro: 2.3841830625315197e-06
Época: 501 erro: 0.0060000065714120865
Época: 1001 erro: 0.010039311833679676
Época: 1501 erro: 0.011265126056969166
Época: 2001 erro: 0.009218982420861721
Época: 2501 erro: 0.006800128147006035


In [42]:
previsoes_teste = mlp(X_teste, W, b)

In [43]:
previsoes_teste

<tf.Tensor: shape=(45, 3), dtype=float32, numpy=
array([[ -6.7580795 ,  -0.66924995,  -3.9014924 ],
       [  3.9416406 ,   0.63281816,  -0.7749664 ],
       [-49.675865  , -10.197209  ,   0.11119729],
       [-10.057941  ,  -1.4386001 ,  -3.5161438 ],
       [-17.373724  ,  -1.7683985 ,  -4.085677  ],
       [  3.9416406 ,   0.63281816,  -0.7749664 ],
       [ -3.0089462 ,  -0.3400336 ,  -2.9469168 ],
       [-32.506367  ,  -5.609302  ,  -1.7541621 ],
       [-21.302597  ,  -3.5654259 ,  -4.4014273 ],
       [ -5.082962  ,  -0.3362912 ,  -3.9911466 ],
       [-21.53911   ,  -3.8991919 ,  -1.7841394 ],
       [  3.9416406 ,   0.63281816,  -0.7749664 ],
       [  3.9416406 ,   0.63281816,  -0.7749664 ],
       [  3.9416406 ,   0.63281816,  -0.7749664 ],
       [  3.9416406 ,   0.63281816,  -0.7749664 ],
       [ -9.79028   ,  -1.0283718 ,  -2.9040024 ],
       [-29.335283  ,  -6.649709  ,  -0.38581103],
       [ -6.1503725 ,  -1.0280714 ,  -3.5939908 ],
       [ -6.046217  ,  -1.0109301

In [44]:
previsoes_teste = tf.nn.softmax(previsoes_teste)

In [45]:
previsoes_teste

<tf.Tensor: shape=(45, 3), dtype=float32, numpy=
array([[2.1771928e-03, 9.5993525e-01, 3.7887584e-02],
       [9.5647585e-01, 3.4967992e-02, 8.5561341e-03],
       [2.3863742e-22, 3.3350421e-05, 9.9996662e-01],
       [1.6045525e-04, 8.8855869e-01, 1.1128082e-01],
       [1.5201159e-07, 9.1029787e-01, 8.9702018e-02],
       [9.5647585e-01, 3.4967992e-02, 8.5561341e-03],
       [6.0649179e-02, 8.7482047e-01, 6.4530335e-02],
       [4.3190562e-14, 2.0731738e-02, 9.7926831e-01],
       [1.3818627e-08, 6.9762242e-01, 3.0237761e-01],
       [8.3906855e-03, 9.6660781e-01, 2.5001545e-02],
       [2.3499807e-09, 1.0764239e-01, 8.9235765e-01],
       [9.5647585e-01, 3.4967992e-02, 8.5561341e-03],
       [9.5647585e-01, 3.4967992e-02, 8.5561341e-03],
       [9.5647585e-01, 3.4967992e-02, 8.5561341e-03],
       [9.5647585e-01, 3.4967992e-02, 8.5561341e-03],
       [1.3575815e-04, 8.6699069e-01, 1.3287352e-01],
       [2.6704097e-13, 1.9001921e-03, 9.9809986e-01],
       [5.5063060e-03, 9.2352241e

In [46]:
previsoes_teste = tf.argmax(previsoes_teste, axis = 1).numpy()

In [47]:
previsoes_teste

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [49]:
y_teste2 = tf.argmax(Y_teste, axis = 1).numpy()

In [50]:
y_teste2

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [51]:
from sklearn.metrics import accuracy_score

In [52]:
taxa_acerto = accuracy_score(y_teste2, previsoes_teste)

In [53]:
taxa_acerto

1.0