In [1]:
import tensorflow as tf
import numpy as np

# **Valore de Entrada**

In [2]:
X = np.array( [ [0,0], [0,1], [1,0], [1,1] ] )

In [3]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

# **Resposta Correta**

In [4]:
Y = np.array( [ [1], [0], [0], [1] ] )

In [5]:
Y

array([[1],
       [0],
       [0],
       [1]])

# **Qtd de Neuronios nas camadas**

In [6]:
neuronios_entrada = 2
neuronios_ocultas = 3
neuronios_saida = 1

#**Convertendo os array em tensor**

In [7]:
X = tf.convert_to_tensor(X, dtype = tf.float32, name = 'X')
Y = tf.convert_to_tensor(Y, dtype = tf.float32, name = 'Y')

#**Criando as camadas**

**LEMBRANDO**

Funções lineares

f(x) = W*x + b

ou

Y = a*X + b

In [8]:
W = {'oculta': tf.Variable( tf.keras.backend.random_normal( shape=( neuronios_entrada, neuronios_ocultas ) ), name='w_oculta' ),
     'saida':  tf.Variable( tf.keras.backend.random_normal( shape=( neuronios_ocultas, neuronios_saida ) ), name='w_saida' ),}

In [9]:
type(W)

dict

In [10]:
type(W['oculta'])

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [11]:
W['oculta']

<tf.Variable 'w_oculta:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.13158542,  0.47027856,  1.9270324 ],
       [ 0.34222168, -0.8065564 ,  1.3240298 ]], dtype=float32)>

In [12]:
W['saida']

<tf.Variable 'w_saida:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.1814514 ],
       [-0.87306243],
       [ 0.5319728 ]], dtype=float32)>

In [13]:
b = {'oculta': tf.Variable( tf.keras.backend.random_normal( shape = (neuronios_ocultas,) ), name='b_oculta' ) ,
     'saida':  tf.Variable( tf.keras.backend.random_normal( shape = (neuronios_saida,) ), name='b_saida' )}

In [14]:
b['oculta']

<tf.Variable 'b_oculta:0' shape=(3,) dtype=float32, numpy=array([ 1.0241584 , -0.14229487,  1.3928986 ], dtype=float32)>

In [15]:
b['saida']

<tf.Variable 'b_saida:0' shape=(1,) dtype=float32, numpy=array([0.88216674], dtype=float32)>

#**Fazendo as contas**

**Ajustando os valores de W e b, com backpropagation e diminuindo o erro com o MSE**

In [16]:
otimizador = tf.keras.optimizers.SGD(learning_rate = 0.3)

for epoca in range(10000):
    with tf.GradientTape() as tape:
        camada_oculta = tf.add(tf.matmul(X, W['oculta']), b['oculta'])
        camada_oculta_ativacao = tf.sigmoid(camada_oculta)
        camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W['saida']), b['saida'])
        camada_saida_ativacao = tf.sigmoid(camada_saida)
        erro = tf.keras.losses.MSE(Y, camada_saida_ativacao)

    var_list = [W['oculta'], W['saida'], b['oculta'], b['saida']]
    
    gradientes = tape.gradient(erro, var_list)
    
    otimizador.apply_gradients(zip(gradientes, var_list))

    if epoca % 200 == 0:
        erro_medio = tf.reduce_mean(erro).numpy()
        print(erro_medio)

0.2534378
0.23928815
0.1887624
0.15022203
0.13827944
0.1334598
0.13098389
0.12949304
0.12847972
0.1277
0.12697253
0.12592223
0.119319424
0.019698769
0.008865533
0.0057777753
0.004267895
0.003366985
0.0027688376
0.002343603
0.0020263712
0.0017810466
0.0015859508
0.0014272822
0.0012958522
0.0011853059
0.0010911014
0.0010099355
0.0009393131
0.0008773461
0.00082256086
0.00077380834
0.0007301574
0.0006908645
0.00065532443
0.0006230317
0.00059357693
0.00056660245
0.0005418174
0.0005189757
0.00049785885
0.0004782849
0.00046009332
0.0004431489
0.00042733038
0.00041253012
0.000398657
0.00038562695
0.00037336862
0.00036181934


#**Valores de W e B**

In [17]:
W

{'oculta': <tf.Variable 'w_oculta:0' shape=(2, 3) dtype=float32, numpy=
 array([[ 5.4468603 ,  5.889037  ,  6.0019355 ],
        [ 7.489538  , -7.7819324 , -0.94466704]], dtype=float32)>,
 'saida': <tf.Variable 'w_saida:0' shape=(3, 1) dtype=float32, numpy=
 array([[-8.558586],
        [-8.917947],
        [ 8.611229]], dtype=float32)>}

In [18]:
b

{'oculta': <tf.Variable 'b_oculta:0' shape=(3,) dtype=float32, numpy=array([-2.3534975, -2.891541 , -1.6267194], dtype=float32)>,
 'saida': <tf.Variable 'b_saida:0' shape=(1,) dtype=float32, numpy=array([4.0539474], dtype=float32)>}

#**TESTE**

In [19]:
camada_oculta_teste = tf.add(tf.matmul(X, W['oculta']), b['oculta'])
camada_oculta_ativacao_teste = tf.sigmoid(camada_oculta_teste)
camada_saida_teste = tf.add(tf.matmul(camada_oculta_ativacao_teste, W['saida']), b['saida'])
camada_saida_ativacao_teste = tf.sigmoid(camada_saida_teste)

In [20]:
camada_saida_ativacao_teste

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.9860327 ],
       [0.02097172],
       [0.01593545],
       [0.97731006]], dtype=float32)>