In [2]:
import tensorflow as tf
import numpy as np

In [3]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])

In [7]:
Y = np.array([[0.0], [1.0], [1.0], [1.0]])

In [5]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [8]:
Y

array([[0.],
       [1.],
       [1.],
       [1.]])

In [9]:
W = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))

In [10]:
def step(x):
    return tf.cast(tf.math.greater_equal(x, 1), tf.float64)

In [11]:
epoca = 0
for i in range(15):
    epoca += 1
    
    # Forward pass
    camada_saida = tf.matmul(X, W)
    camada_saida_ativacao = step(camada_saida)
    
    # Backpropagation
    erro = tf.subtract(y, camada_saida_ativacao)
    delta = tf.matmul(X, erro, transpose_a = True)
    W.assign_add(tf.multiply(delta, 0.1))
    
    # Resumo da época
    erro_soma = tf.reduce_sum(erro).numpy()
    print('Época:', epoca, ' Erro: ', erro_soma)
    if erro_soma == 0.0:
        break

Época: 1  Erro:  3.0
Época: 2  Erro:  3.0
Época: 3  Erro:  3.0
Época: 4  Erro:  2.0
Época: 5  Erro:  2.0
Época: 6  Erro:  2.0
Época: 7  Erro:  2.0
Época: 8  Erro:  0.0


In [12]:
W

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[1.],
       [1.]])>

In [13]:
camada_saida_teste = tf.matmul(X, W)
camada_saida_ativacao_teste = step(camada_saida_teste)
camada_saida_ativacao_teste.numpy()

array([[0.],
       [1.],
       [1.],
       [1.]])