#**Operador OR**

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0],])

In [3]:
print(X)

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [4]:
Y = np.array([[0.0], [0.0], [0.0], [1.0]])    

In [5]:
Y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [6]:
W = tf.Variable(tf.zeros([2,1], dtype = tf.float64))

In [7]:
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[0.],
       [0.]])>


In [8]:
def step(x):
  return tf.cast( tf.math.greater_equal(x, 1), dtype=tf.float64 )

In [9]:
camada_saida = tf.matmul(X, W)

In [10]:
camada_saida

<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]])>

In [11]:
camada_saida_ativacao = step(camada_saida)

In [12]:
camada_saida_ativacao

<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]])>

In [13]:
erro = tf.subtract(Y, camada_saida_ativacao)

In [14]:
erro

<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[0.],
       [0.],
       [0.],
       [1.]])>

In [15]:
delta = tf.matmul( X, erro, transpose_a=True )

In [16]:
treinamento = W.assign( tf.add(W, tf.multiply(delta, 0.1) ) )

In [17]:
print(treinamento)

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=float64, numpy=
array([[0.1],
       [0.1]])>


In [18]:
epoca = 0
for i in range(15):
  epoca += 1
  erro = tf.subtract(Y, step( tf.matmul(X, W) ) )
  delta = tf.matmul(X, erro, transpose_a = True )
  treinamento = W.assign( tf.add(W, tf.multiply( delta, 0.1 ) ) )
  erro_soma = tf.reduce_sum(erro)
  print('Época = ', epoca, ' Erro = ', erro_soma.numpy())
  if erro_soma.numpy() == 0.0 : break

Época =  1  Erro =  1.0
Época =  2  Erro =  1.0
Época =  3  Erro =  1.0
Época =  4  Erro =  1.0
Época =  5  Erro =  0.0


In [19]:
W

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[0.5],
       [0.5]])>

In [20]:
camada_saida_teste = tf.matmul(X, W)

In [21]:
camada_saida_ativacao_teste = step(camada_saida_teste)

In [22]:
camada_saida_ativacao_teste

<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[0.],
       [0.],
       [0.],
       [1.]])>